// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
 "use client";

import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const hideChrome = pathname === "/chat" || pathname === "/Room1";

  return (
    <html lang="en">
      <body className="bg-slate-950 text-white">
        {!hideChrome && (
          <header className="w-full px-6 py-4 flex items-center justify-between bg-white/5 backdrop-blur-md border-b border-white/10 sticky top-0 z-50">
            <Link
              href="/"
              className="text-xl font-extrabold bg-gradient-to-r from-pink-400 via-purple-400 to-blue-400 bg-clip-text text-transparent"
            >
              NextChat
            </Link>
            <nav className="flex gap-5 text-sm font-medium text-white/70">
              <Link href="/" className="hover:text-white transition">
                Home
              </Link>
              <Link href="/about" className="hover:text-white transition">
                About
              </Link>
            </nav>
          </header>
        )}

        <main>{children}</main>

        {!hideChrome && (
          <footer className="w-full px-6 py-4 text-center text-xs text-white/40 border-t border-white/10 bg-white/5">
            © {new Date().getFullYear()} NextChat — built for educational purposes only.
          </footer>
        )}
      </body>
    </html>
  );
}